name: w3college-backend

services:
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE:-w3college}
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-123456}
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8'
    ports:
      - '${DB_PORT:-5432}:5432'
    volumes:
      - ./localStoreData/postgres:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - '${REDIS_PORT:-6379}:6379'
    volumes:
      - ./localStoreData/redis:/data
    command: redis-server --appendonly yes